- name: Configure MYSQL Server
  hosts: mysql
  become: yes # become Root User
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: Install MYSQL Libraries
    ansible.builtin.pip:
      name: {{ item }}
      executable: pip3:9
    loop:
    - cryptography
    - PyMySQL

  
  - name: Install MYSQL Server
    ansible.builtin.package:
      name: mysql-server
      state: installed
  
  - name: start & enable MYSQL Service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to MYSQL Server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.kumardevops.store
    register: mysql_info
    ignore_errors: true
  
  - name: Print the Output
    ansible.builtin.debug:
      msg: " MYSQL Info: {{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true

    