- name: Configure MYSQL Server in AWS Linux instance
  hosts: 
  become: yes
  tasks:
    - name: Install MYSQL software i.e., MYSQL service get enabled
      ansible.built-in.package:
        name: mysql-server
        state: installed

    - name: Start & enable MYSQL service
      ansible.built-in.service:
        name: mysqld
        state: started
        enabled: yes



